modLoader = "javafml"
loaderVersion = "[47,)"
license = "GNU GENERAL PUBLIC LICENSE"
[[mods]]
modId = "reabista"
version = "1.2.20"
displayName = "Re:Abista"
authors = "kaede"
description = ''''''

[[dependencies.reabista]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.reabista]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,1.21)"
ordering = "NONE"
side = "BOTH"
